#!/bin/bash
XENSTOREREAD=`which xenstore-read`
if [ -e $XENSTOREREAD ]; then
  NAME=`$XENSTOREREAD name`
  DOMAIN=`$XENSTOREREAD vm-data/dm`

  [ "$NAME" = "" ] && exit 0
  echo "$NAME" > /etc/hostname
  /bin/hostname -F /etc/hostname


cat << EOF > /etc/hosts
127.0.0.1	localhost $NAME	
EOF

fi
exit 0

